sudo: required
services:
    - docker

    before_install:
        - docker build -t vvsvalasala/pradeep-docker-react -f Dockerfile.dev .

script:
    - docker run vvsvalasala/pradeep-docker-react npm test -- -- coverage
