sudo: required
services:
    - docker

    before_install:
        - docker build -t vvsvalasala/pradeep-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vvsvalasala/pradeep-docker-react npm run test
